# Generated by Django 4.0.3 on 2022-03-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('ADVOCACIA', 'Advocacia'), ('SAUDE', 'Saúde'), ('ASSISTENCIA_TECNICA', 'Assistência Técnica'), ('CONSTRUCAO_CIVIL', 'Construção Civil'), ('BELEZA', 'Beleza'), ('EDUCACAO', 'Educação'), ('SERVICOS_DOMESTICOS', 'Serviços Domésticos'), ('DESIGN', 'Design')], max_length=25),
        ),
    ]
