# Generated by Django 4.0.3 on 2022-04-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='uf',
            field=models.CharField(choices=[{'AC', 'ac'}, {'AL', 'al'}, {'am', 'AM'}, {'AP', 'ap'}, {'BA', 'ba'}, {'ce', 'CE'}, {'df', 'DF'}, {'ES', 'es'}, {'go', 'GO'}, {'MA', 'ma'}, {'MG', 'mg'}, {'ms', 'MS'}, {'mt', 'MT'}, {'PA', 'pa'}, {'pb', 'PB'}, {'PE', 'pe'}, {'PI', 'pi'}, {'pr', 'PR'}, {'rj', 'RJ'}, {'rn', 'RN'}, {'RO', 'ro'}, {'RR', 'rr'}, {'RS', 'rs'}, {'SC', 'sc'}, {'SE', 'se'}, {'sp', 'SP'}, {'to', 'TO'}], max_length=2),
        ),
    ]
