# Generated by Django 4.0.3 on 2022-04-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_company_address_alter_company_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='uf',
            field=models.CharField(choices=[('AC', 'ac'), ('AL', 'al'), ('AM', 'am'), ('AP', 'ap'), ('BA', 'ba'), ('CE', 'ce'), ('DF', 'df'), ('ES', 'es'), ('GO', 'go'), ('MA', 'ma'), ('MG', 'mg'), ('MS', 'ms'), ('MT', 'mt'), ('PA', 'pa'), ('PB', 'pb'), ('PE', 'pe'), ('PI', 'pi'), ('PR', 'pr'), ('RJ', 'rj'), ('RN', 'rn'), ('RO', 'ro'), ('RR', 'rr'), ('RS', 'rs'), ('SC', 'sc'), ('SE', 'se'), ('SP', 'sp'), ('TO', 'to')], max_length=2),
        ),
    ]
